meta_product_name: "Seven Consulting"
meta_title: "Seven Consulting"
meta_description: "Building Simulation, Energy and Sustainability"
meta_image: "seven-cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
